---
- name: User | Creating users with docker access
  user:
    name: "{{ user_name }}"
    state: present
    comment: "{{ user_comment }}"
    password: "{{  user_password | password_hash('sha512','A512') }}"
    update_password: on_create
    createhome: yes
    groups: "docker"
  tags:
    - user
    - docker_access
