---
# tasks file for ansible-role-docker

- include_tasks: install.RedHat.yml
  when: ansible_os_family == "RedHat"

- include_tasks: install.Ubuntu.yml
  when: ansible_os_family == "Debian"

- include_tasks: config.swap_limit_capabilities.yml
  when: ansible_os_family == "Debian"

- include_tasks: config.users.yml
  when: setup_user

- include_tasks: install.docker_compose.yml
  when: install_docker_compose

- name: flush_handlers
  meta: flush_handlers
