---
# tasks file for ansible-role-docker

- include: install.RedHat.yml
  when: ansible_os_family in ['RedHat', 'Rocky']

- include: install.Ubuntu.yml
  when: ansible_os_family == "Debian"

- include: config.swap_limit_capabilities.yml
  when: ansible_os_family == "Debian"

- include: config.users.yml

- include: install.docker_compose.yml
  when: install_docker_compose

- name: flush_handlers
  meta: flush_handlers
